spring:
  datasource:
    username: root 
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reportapi 
    
    
  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true  
      